name: Tests

on:
  push:

jobs:
  api:
    name: Code Style Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Install Hurl
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/4.0.0/hurl_4.0.0_amd64.deb
          sudo dpkg -i hurl_4.0.0_amd64.deb

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --ignore-platform-reqs

      - name: Run code style check
        run: composer lint

      - name: Run static analysis
        run: composer check

      - name: Run PHP server
        run: php -S 0.0.0.0:8000 app/http.php

      - name: Run tests
        run: composer test

  docs:
    name: Docs Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci
        working-directory: docs

      - name: Run lint check
        run: npm run lint
        working-directory: docs
