name: Tests

on:
  push:

jobs:
  api:
    name: API (Lint, CodeQL, Tests)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install Hurl
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/4.0.0/hurl_4.0.0_amd64.deb
          sudo dpkg -i hurl_4.0.0_amd64.deb

      - name: Install Appwrite CLI
        run: npm install -g appwrite-cli
        
      - name: Authenticate Appwrite CLI
        run: appwrite client --project-id ${{ secrets._APP_APPWRITE_PROJECT_ID }} --endpoint ${{ secrets._APP_APPWRITE_ENDPOINT }} --key ${{ secrets._APP_APPWRITE_KEY }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --ignore-platform-reqs

      - name: Run code style check
        run: composer lint

      - name: Run static analysis
        run: composer check
        
      - name: Prepare environment
        run: |
          touch .env
          echo "_APP_MODE=development" >> .env
          echo "_APP_APPWRITE_PROJECT_ID=${{ secrets._APP_APPWRITE_PROJECT_ID }}" >> .env
          echo "_APP_APPWRITE_ENDPOINT=${{ secrets._APP_APPWRITE_ENDPOINT }}" >> .env
          echo "_APP_APPWRITE_KEY=${{ secrets._APP_APPWRITE_KEY }}" >> .env

      - name: Run PHP server
        run: php -S 0.0.0.0:8000 app/http.php &> server.log

      - name: Wait for server to be ready
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8000 > /dev/null 2>&1; then
              echo "Server is ready"
              break
            fi
            echo "Waiting for server... ($i/30)"
            sleep 1
          done

      - name: Run tests
        run: composer test
        
      - name: Print logs
        run: cat server.log
        if: failure()

  docs:
    name: Docs (lint, build)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci
        working-directory: docs

      - name: Run lint check
        run: npm run lint
        working-directory: docs

      - name: Run build
        run: npm run build
        working-directory: docs
